apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prawoasystent-api-ingress
  namespace: prawoasystent-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://prawoasystent.ai"
spec:
  tls:
  - hosts:
    - api.prawoasystent.ai
    secretName: prawoasystent-api-tls
  rules:
  - host: api.prawoasystent.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prawoasystent-api-service
            port:
              number: 80
