apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prawoasystent-api-pdb
  namespace: prawoasystent-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: prawoasystent-api
