apiVersion: v1
kind: Service
metadata:
  name: prawoasystent-api-service
  namespace: prawoasystent-prod
  labels:
    app: prawoasystent-api
spec:
  selector:
    app: prawoasystent-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
